#if defined(__cplusplus)
extern "C" {
#endif
	LONG WINAPI C3SENDCOMMAND( HANDLE hComDev, BYTE RsCode, BYTE RsCla, BYTE RsIns, BYTE RsP1, BYTE RsP2, BYTE RsP3, LPBYTE RsData, LPBYTE RsSW1, LPBYTE RsSW2, LPINT RsLen, LONG TimeOut );
	LONG WINAPI C3ICCSTATUS( HANDLE hComDev, int CCA );
	LONG WINAPI C3INSERT( HANDLE hComDev, int CCA, LONG TimeOut );
	LONG WINAPI C3REMOVE( HANDLE hComDev, int CCA, LONG TimeOut );
	LONG WINAPI C3ISOIN( HANDLE hComDev, int CCA, BYTE Cla, BYTE Ins, BYTE P1, BYTE P2, BYTE P3, LPBYTE Data, LPBYTE SW1, LPBYTE SW2, LONG TimeOut );
 	LONG WINAPI C3ISOOUT( HANDLE hComDev, int CCA, BYTE Cla, BYTE Ins, BYTE P1, BYTE P2, BYTE P3, LPBYTE Data, LPBYTE SW1, LPBYTE SW2, LONG TimeOut );
 	LONG WINAPI C3POWERON( HANDLE hComDev, int CCA, int CardType, LPINT LATR, LPBYTE ATR, LPBYTE SW1, LPBYTE SW2 );
	LONG WINAPI C3POWEROFF( HANDLE hComDev, int CCA );
	LONG WINAPI C3RESET( HANDLE hComDev, LPINT LATR, LPSTR ATR );
	LONG WINAPI C3IFDSTATUS( HANDLE hComDev );
	BOOL WINAPI C3CARDINSERTED( HANDLE hCommDev, int CCA );
	BOOL WINAPI C3READERPOWERED( HANDLE hCommDev );
	HANDLE WINAPI C3OPEN( LPSTR Port );
	BOOL WINAPI C3CLOSE( HANDLE hComDev );
#if defined(__cplusplus)
}
#endif	
