//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by sexshop.rc
//
#define ID_MONEDA_EUROS                 0
#define ST_ENCENDIDO                    0x01
#define PING_MSG                        0x01
#define PONG_MSG                        0x01
#define ID_MONEDA_PESETAS               1
#define ERROR_CABINA                    2
#define ERROR_GENERAL                   3
#define ERROR_COMUNICACIONES			4
#define IDCANCEL2                       3
#define RESET_MSG                       4
#define NUM_INTENTOS                    5
#define NUM_COLUMNS                     8
#define IDD_ABOUTBOX                    100
#define IDD_SEXSHOP_FORM                101
#define IDD_LISTPAGE1                   103
#define IDD_LISTPAGE2                   104
#define IDT_TIMER1                      105
#define IDD_LISTSETUP                   105
#define IDD_PRINT_STATUS                106
#define IDT_TIMER2                      114
#define IDB_BITMAP31                    120
#define ID_MY_STATUS_BAR                123
#define IDR_MAINFRAME                   128
#define IDR_SEXSHOTYPE                  129
#define IDR_PRINT                       129
#define IDB_LUCES                       130
#define IDC_HANDCUR                     130
#define IDB_CANAL                       131
#define IDB_PAGE                        132
#define IDD_DIALOG_BORRAR               137
#define IDD_DIALOG1                     138
#define IDD_DIALOG2                     141
#define IDD_DIALOG3                     142
#define IDB_BITMAP1                     143
#define IDD_DIALOG4                     144
#define IDB_BITMAP3                     146
#define IDB_BITMAP2                     150
#define IDB_BITMAP4                     151
#define IDB_BITMAP5                     153
#define IDB_BITMAP6                     154
#define IDD_MONITOR                     155
#define IDD_HISTORIAL                   156
#define IDD_DIALOG_HISTO                157
#define IDD_IMPRIMIENDO                 158
#define IDB_BITMAP7                     159
#define IDD_CONFIG_COINTIME             160
#define IDB_MENUTEXT                    163
#define IDR_POPUP                       164
#define IDB_INICIALIZA_FICHERO          165
#define IDR_POPUP2                      165
#define IDB_INICIALIZA_SELECCION        166
#define IDB_IMPRIMIR                    167
#define IDB_VER_HISTORIAL               168
#define IDB_VER_MONITOR                 169
#define IDB_OCULTAR                     170
#define IDD_CONTROL                     174
#define IDI_LED_APAGADO                 177
#define IDI_LED_ENCENDIDO               178
#define IDB_RESET                       179
#define IDI_LED_APAGADO_VERDE           179
#define IDB_SWITCH                      180
#define IDI_LED_ENCENDIDO_VERDE1        180
#define IDB_BITMAP9                     184
#define IDB_MTX15                       186
#define IDB_MTX15_TEXT                  189
#define IDD_LEER_TARJETA                190
#define IDD_MENSAJE                     191
#define IDR_TECNICO                     193
#define IDD_CABINAS_PROP                195
#define IDB_BITMAP8                     197
#define IDB_OSD                         198
#define IDB_PULSADORES                  199
#define IDR_CABINAPROP                  200
#define CTRL_MSG                        0xff
#define IDC_LIST1                       1000
#define IDC_LIST2                       1001
#define IDC_EDIT1                       1006
#define IDC_SPIN1                       1007
#define IDC_TOTAL_TARJETAS              1007
#define IDC_EDIT2                       1008
#define IDC_ENTRADAS                    1008
#define IDC_PROGRESS1                   1009
#define IDC_DISPLAY_ENTRADAS            1009
#define IDC_TAB1                        1010
#define IDC_DISPLAY_SALIDAS             1010
#define IDC_ANIMATE1                    1011
#define IDC_BT_PRINTOPT                 1013
#define IDC_DESACTIVAR                  1013
#define IDC_APAGAR                      1014
#define IDC_ENCENDER                    1015
#define IDC_RESET                       1016
#define IDC_PETICION_SI                 1017
#define IDC_LUZON                       1018
#define IDC_LED_APAGADO                 1018
#define IDC_PETICION_NO                 1018
#define IDC_BUTTON1                     1020
#define IDC_ED_MMSX                     1021
#define IDC_RADIO1                      1022
#define IDC_RADIO2                      1023
#define RX_STATUS                       0x400
#define IDC_BUTTON2                     1024
#define MON_PING                        0x401
#define IDC_HISTORIAL                   1025
#define IDC_MENSAJES_TECLA              1025
#define MON_PONG                        0X402
#define IDC_CABINAS                     1026
#define RX_BYTE                         0x403
#define IDC_CANALES                     1027
#define IDC_ED_MMDOWN                   1027
#define IDC_IMPRIMIR                    1028
#define MON_RESET                       0x404
#define IDC_SPIN4                       1028
#define MON_MONEDA                      0x405
#define IDC_PAGINA                      1030
#define IDC_ED_MMUP                     1030
#define IDC_MSCOMM1                     1031
#define IDC_ED_MMDX                     1031
#define TO_WTCABINAS                    1032
#define TO_RESETPC                      1033
#define IDC_DIVIDER_SMALL               1034
#define TO_GENERAL_DESCUENTO            1034
#define IDC_COMPORT                     1035
#define IDC_COMPORT_TARJETAS            1036
#define IDC_TIPO_MONEDA                 1037
#define IDC_PC                          1037
#define IDC_DATOS_RX                    1038
#define IDC_TEXT1                       1038
#define IDC_DATOS_TX                    1039
#define IDC_PAGES                       1039
#define IDC_TOTAL_CABINAS               1041
#define IDC_SPIN2                       1042
#define IDC_TOTAL_CANALES               1043
#define IDC_NUM_SERIE                   1043
#define IDC_SPIN3                       1044
#define IDC_OLD_IMPORTE                 1044
#define IDC_MENSAJE                     1045
#define IDC_IMPORTE                     1046
#define IDC_TIPO_MONEDA2                1047
#define IDC_DIVIDER                     1049
#define IDC_CREAR_TECNICO               1050
#define IDC_EDFOOTER                    1050
#define IDC_TARJETA_TIPO                1051
#define IDC_CBFHEAD                     1052
#define IDC_IMPRIMIR_CANALES            1052
#define IDC_CBSHEAD                     1053
#define IDC_CANAL_INICIAL               1053
#define IDC_CBFFOOTER                   1054
#define IDC_CANAL_FINAL                 1054
#define IDC_CBSFOOTER                   1055
#define IDC_VALOR_1                     1055
#define IDC_CBFCORPO                    1056
#define IDC_VALOR_2                     1056
#define IDC_CBSCORPO                    1057
#define IDC_VALOR_DESCUENTO             1057
#define IDC_EDHEAD                      1058
#define IDC_CHECK1                      1058
#define IDC_EDPAGE                      1059
#define IDC_CREDITO                     1059
#define IDC_OCULTAR_CANAL               1059
#define IDC_CANAL                       1060
#define IDC_SALTAR_CANALES              1060
#define IDC_TIEMPO                      1061
#define IDC_OCULTAR_CANAL3              1061
#define IDC_LUZ_ACTIVA                  1062
#define IDC_ACUMULADO                   1063
#define IDC_NUMERO                      1064
#define IDC_ESTADO                      1065
#define IDC_LUZ_ESTADO                  1066
#define IDC_EDIT4                       1069
#define IDC_ENVIAR_TEXTO                1069
#define IDC_CANAL_ACT                   1071
#define IDC_APLICAR                     1072
#define IDC_OCULTAR_CREDITO             1073
#define IDC_SEGUNDOS_CREDITO            1074
#define IDC_TECLA_ACTUA                 1077
#define IDC_TECLA_NO_ACTUA              1078
#define IDC_MENSAJES_TIEMPO             1079
#define IDC_SALIDAS                     1079
#define IDC_BORRAR_ESTADISTICAS         1080
#define IDC_MOSTRAR_CANAL               1080
#define IDC_SLIDER1                     1081
#define IDC_ENVIAR                      1082
#define IDC_BORRAR_TEXTO                1083
#define IDC_BUTTON3                     1086
#define ID_FILE_ERASE                   32771
#define ID_BORRAR_CANAL                 32772
#define ID_BORRAR_CABINA                32774
#define ID_EDICIN_BORRARCANAL           32775
#define ID_EDICIN_BORRARCABINA          32776
#define ID_VER_REFRESCOAUTOMTICO        32777
#define ID_ARCHIVO_DESACTIVAR           32778
#define ID_ARCHIVO_OCULTAR              32779
#define ID_EDICIN_CAMBIARPASSOWRD       32780
#define ID_VIEW_MONITOR                 32782
#define ID_HISTORIAL_VERHISTORIAL       32783
#define ID_EDICIN_TIEMPOMON             32785
#define ID_INICIALIZARCANAL             32787
#define ID_IMPRIMIR                     32788
#define ID_INICIALIZARCABINA            32793
#define ID_VER_PANELDECONTROLDECONSOLA  32794
#define ID_TARJETAS_NUEVA               32796
#define ID_TARJETAS_LEER                32797
#define ID_EDICIN_CAMBIARPASSOWRD_DEPENDIENTE 32798
#define ID_THREAD_ON                    32800
#define ID_THREAD_OFF                   32802
#define ID_SIMULACION_ON                32803
#define ID_SIMULACION_OFF               32804
#define ID_PROPIEDADESDECABINA          32807
#define ID_INICIAR_CABINA               32813
#define ID_CABINA_ACTIVAR               32816
#define ID_CABINA_DESACTIVAR            32817
#define ID_CABINA_BLOQUEAR              32818
#define ID_DESBLOQUEAR                  32819
#define ID_MATRIZ_REINICIAR             32822
#define ID_MATRIZ_DETENERTODASLASCABINAS 32823
#define ID_MATRIZ_ACTIVARTO             32824
#define ID_CANALMAS                     32825
#define ID_CANALMENOS                   32826
#define ID_INDICATOR_FECHA              59142
#define ID_INDICATOR_TOTAL              59143
#define ID_INDICATOR_TARJETAS           59144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           124
#endif
#endif
